name = "ip6calc"
main = "worker/index.js"
compatibility_date = "2024-01-01"

assets = { directory = "./dist", binding = "ASSETS" }

[[routes]]
pattern = "ipcalc.williamfinken.com"
custom_domain = true